set number
set smartindent
set ignorecase smartcase
set nowrap
set et sw=2 ts=2
set hidden
set clipboard=unnamed
set backspace=indent,eol,start
set hls

set textwidth=110 colorcolumn=110

map K r<CR>
map =j :%!python -m json.tool<CR>

execute pathogen#infect()

syntax on
filetype plugin indent on
"autocmd FileType scala setlocal shiftwidth=2 tabstop=2
