set number
set smartindent
set ignorecase smartcase
set nowrap
set et sw=2 ts=2
set hidden
set clipboard=unnamed
set backspace=indent,eol,start
set hls

augroup filetypedetect
  au BufRead,BufNewFile *.hamlet setfiletype haskell
augroup END

set textwidth=80 colorcolumn=80
au FileType scala set tw=110 cc=110

map K r<CR>
map =j :%!python -m json.tool<CR>

" trailing spaces highlighting
au FileType *
  \ if &ft == 'diff' |
    \ match Error /\(+.\{-}\)\@<=\s\+$/ |
  \ else |
    \ match Error /\s\+$/ |
  \ endif

execute pathogen#infect()

syntax on
filetype plugin indent on
"autocmd FileType scala setlocal shiftwidth=2 tabstop=2
