# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 4
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd
unsetopt beep extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install

source /etc/zsh/zprofile
source /etc/zsh/zshrc.d/*

setup-distcc() {
  [[ $PATH != *distcc* ]] \
  && export PATH="/usr/lib/distcc/bin:${PATH}"
}

setup-ccache() {
  [[ $PATH != *ccache* ]] && export PATH="/usr/lib/ccache/bin:$PATH"
  export CCACHE_DIR="/home/.ccache"
}

# history lookup using prefixes
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# aliases

alias -s mp4=mpv
alias -s MPG=mpv
alias -s avi=mpv
alias -s mkv=mpv
alias -s flv=mpv
alias -s webm="mpv -loop-playlist=inf"
alias -s pdf=mupdf-x11
alias -s txt=vim
alias -s md=vim
alias -s png="feh -F"
alias -s jpg="feh -F"

alias xc='xclip -i -selection clipboard'
alias xp='xclip -o -selection clipboard'

alias du='du -h'
alias df='df -h'

alias vr="vim ~/.zshrc"
alias svr="sudo vim /etc/zsh/zshrc"
sr() { source /etc/zsh/zshrc; source ~/.zshrc; }

cpv() { stdbuf -o0 cp -rnv "$@" | sed -u 's/.*->/->/'; }
alias rn=perl-rename
alias sed="sed -r"
alias less="less -iSXFR"
alias xs="xargs -I{}"
alias watch-ccache="CCACHE_DIR=/home/.ccache watch -d -n 30 ccache --show-stats"
alias distcc-mon="DISTCC_DIR=/var/tmp/portage/.distcc distccmon-text 3"
alias distcc-mon-h="DISTCC_DIR=/home/.portage/tmp/portage/.distcc distccmon-text 3"

# utilities

x() { sed -n $1p $2; }
esc=$(printf '\033')
alias shorten-paths='sed -e "s|/.+/([^/]+/)|/**/\1|"'
alias dmon="watch -n2 'DISTCC_DIR=/var/tmp/portage/.distcc distccmon-text'"
alias bt-restart="for s in bluetooth bluealsa; do sudo rc-service \$s start; done"

my-sdiff() {
  local S
  for i in "$@"; do
    [ "$i" = -s ] && S=1
  done
  sdiff -tw `tput cols` $@ \
  | ([ $S ] && cat || sed -Ee "s/^(.+ \| .*|.+<| +> .*)$/${esc}[32m\1${esc}[0m/") \
  | less
}

psw() {
  su -c '
  g=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
  if [[ $g = perf* ]]; then
    echo powersave > /sys/devices/system/cpu/cpu[01]/cpufreq/scaling_governor
    echo "CPU downscaled"
    # Network?
    echo 1 > /sys/bus/pci/devices/0000:09:00.0/remove
    rfkill block 2
    echo "Bluetooth disabled"
    powertop --auto-tune
  else
    echo performance > /sys/devices/system/cpu/cpu[01]/cpufreq/scaling_governor
    echo "CPU upscaled"
    rfkill unblock 2
    echo "Bluetooth enabled"
  fi
  '
}
